// Page components (routes/screens)
// Typically connected to features and services

export { DashboardPage } from './DashboardPage'
export { ProfilePage } from './ProfilePage'
export { ProfileSetupPage } from './ProfileSetupPage'
export { BookingPage } from './BookingPage'
export { BookingConfirmationPage } from './BookingConfirmationPage'
export { AppointmentsPage } from './AppointmentsPage'
export { ReschedulePage } from './ReschedulePage'
export { StaffSchedulePage } from './StaffSchedulePage'
export { StaffAppointmentsPage } from './StaffAppointmentsPage'
export { StaffClientsPage } from './StaffClientsPage'
export { BusinessSettingsPage } from './BusinessSettingsPage'
export { AdminUsersPage } from './AdminUsersPage'
export { AdminStaffPage } from './AdminStaffPage'
export { AdminStaffServicesPage } from './AdminStaffServicesPage'
export { AdminServicesPage } from './AdminServicesPage'
export { AdminServiceAvailabilityPage } from './AdminServiceAvailabilityPage'
export { AdminAppointmentsPage } from './AdminAppointmentsPage'
export { AdminCalendarPage } from './AdminCalendarPage'
export { AdminReportsPage } from './AdminReportsPage'
export { StaffAvailabilityPage } from './StaffAvailabilityPage'
export { UnauthorizedPage } from './UnauthorizedPage'
export { NotFoundPage } from './NotFoundPage'
export { SignInPage } from './SignInPage'
